### ISSUE TITLE
Diff Markdown for github text background issue

### ISSUE THREAD

**Issue by CyberMist2** [poychang/github-dark-theme#191]
As you can see in the screenshot regarding the github markdown for diff
The text background is not dark

![image](https://user-images.githubusercontent.com/7664922/83350240-7fc56280-a343-11ea-979b-0158b696c8af.png)

**Comment by poychang** [comment]
Keep original color for difference code is more recognizable. I don't think this should be dark theme.

**Comment by amirtezgalinew** [comment]
![](https://user-images.githubusercontent.com/7664922/83350240-7fc56280-a343-11ea-979b-0158b696c8af.png)
https://github.com/poychang

**Comment by poychang** [comment]
Close it. If you have any new idea. Reopen it.

**Comment by IamCathal** [comment]
This has been bothering me aswell since I first saw it. Here's my proposal for a fix:

Shown below is what a diff looks like without the extension enabled:
![no theme github diff](https://i.imgur.com/CGtIOWb.png)

If you look carefully you'll see that not only is the text colored based on if it's an addition or a deletion, the background is also slightly tinted aswell. The deletion has a background color of `#ffeef0` (which is ever so slightly red) and the addition has background color of `#f0fff4`. It is very subtle without the extension enabled but is very apparent when the extension is enabled.

My proposal is that we should do the same with the darkmode tinted color e.g slightly give the color a red/green tint that would be something like this below:
![theme on new background tint](https://i.imgur.com/W8OiHJd.png)
The color codes I used are `#31161a` for deletions and `#1c291f` for additions. This proposal keeps the colored background and fits doesn't stick out like a sore thumb as it does at the moment. These are just random colors that I chose to look good for a preview and can obviously be changed if this is properly implemented
