### ISSUE TITLE
Glitched dismiss button in notification page.

### ISSUE THREAD

**Issue by CyberByte-js** [poychang/github-dark-theme#268]
https://github.com/notifications

You can see that the button is with a white border and there is a square around it with a different color.

![image](https://user-images.githubusercontent.com/71409005/96629714-60c36f00-12ea-11eb-9f1f-a06609ce866c.png)

**Comment by IamCathal** [comment]
Could you leave a comment detailing how to see that button. I can't get it to appear

**Comment by CyberByte-js** [comment]
> Could you leave a comment detailing how to see that button. I can't get it to appear

I think it just appear sometimes, this is probably why it is glitched.

**Comment by TakahisaHayashi** [comment]
Hello.
Thank you for letting me use your software here.
I'm going to post a picture on the notification page for your information.

![image](https://user-images.githubusercontent.com/57127872/96740595-f0a50e00-13fb-11eb-9915-55ff15b01b40.png)

I did a little research and it seems to be caused by a CSS class called `.js-notice-dismiss`.

![image](https://user-images.githubusercontent.com/57127872/96741006-572a2c00-13fc-11eb-82ad-0171eeeded47.png)

I'm not very familiar with it, but I see the comment `Issue-#140`, so maybe it's the part that someone fixed before.

Perhaps applying `$bg-color` might fix it.

If I'm wrong, then I'm sorry.
I'd be very happy to help you improve.

**Comment by CyberByte-js** [comment]
Thank you!
