### ISSUE TITLE
Dark theme is not working well in GitHub Docs

### ISSUE THREAD

**Issue by Kygekraqmak** [poychang/github-dark-theme#326]
There should be some improvements for dark theme in GitHub Docs. Currently, there are some objects that did not render properly, such as these:

![image](https://user-images.githubusercontent.com/68368066/100983624-85b32f00-3584-11eb-8442-3c30b4163311.png)

_Source: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions_

**How to Reproduce:**
1. Click the **GitHub Dark Theme** extension at the upper right corner on Google Chrome
2. Add **docs.github.com** in **Included Domain**
3. Open any page you like in GitHub Docs (e.g. https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions)

**Any fixes would be very appreciated!**

**Comment by IamCathal** [comment]
Even though reproducing the issue is very easy I appreciate you writing out the steps, that's always great to see :) 

The way the extension works is it targets elements with specific selectors to change the appearence and obviously github docs isn't using the same ones as github for certain elements. If @poychang thinks adding the necessary code to cover [docs.github.com](https://docs.github.com/) would be a worthwhile I'd be happy to go ahead and do it.
